AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"

Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 110

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Lint/BooleanSymbol:
  Exclude:
    - "test/**/*"
    - "bin/**/*"
Style/HashLikeCase:
  Enabled: false
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
